### ISSUE TITLE
No such file or directory/env: ruby

### ISSUE THREAD

**Issue by nbogda** [slrbl/human-in-the-loop-machine-learning-tool-tornado#4]
When running docker-compose up, I get the error "No such file or directory/env: ruby". I have attached a screenshot of the error I am getting. Because of this error, 0.0.0.0:3000 doesn't have anything on it. Is there something I need to do with ruby to get this up and running? Thanks in advance.

![image](https://user-images.githubusercontent.com/21373166/78930814-b7660b80-7a72-11ea-89c9-44c7868b0fd2.png)

**Comment by slrbl** [comment]
It should be OK now, let me know if you are still facing the same problem
