### ISSUE TITLE
Elastic Search: [ERROR][o.e.g.GatewayMetaState   ] [swoqVS5] failed to read local state, exiting...

### ISSUE THREAD

**Issue by nbogda** [slrbl/human-in-the-loop-machine-learning-tool-tornado#5]
I managed to get the page pulled up at 0.0.0.0:3000, but when I try to upload the Kaggle autism screening for toddlers data set, I run into the same issue as Issue #2. 

![website_issue](https://user-images.githubusercontent.com/21373166/79260503-61bba580-7e5c-11ea-97bd-fb35a458a9e8.png)

It is definitely a problem with elastic search, based on the below error messages. The application then outputs a message that elastic search has exited with code 1. This causes kibana to repeatedly output that there is no live connection at http://elasticsearch:9200.

![elastic_search_error](https://user-images.githubusercontent.com/21373166/79260817-e0184780-7e5c-11ea-9893-a9b5e8daaa4c.png)

I saw that Issue #2 is similar to mine, but I am unsure how to follow since the repository has a very different structure now. I tried downloading elastic search and putting it into the directory manually, but that didn't seem to work. Thanks in advance.

**Comment by slrbl** [comment]
Are you able to load 0.0.0.0:9200 in your browser?

**Comment by nbogda** [comment]
I am not able to load it, no.

**Comment by slrbl** [comment]
Could you try to use a higher version of Elasticsearch ? you can upgrade it in docker-compose.yml line 9, and then build/up again

**Comment by nbogda** [comment]
I used a higher version of elasticsearch, and then tried to upgrade kibana as well (both to 7.6.2). I am now getting an error that the bootstrap checks failed and that the process is exiting with code 78.

![image](https://user-images.githubusercontent.com/21373166/79350636-b6672b00-7f05-11ea-991b-7756cb74141e.png)

**Comment by slrbl** [comment]
You need to remove the ./elasticserach folder before building with t he new version

**Comment by nbogda** [comment]
I deleted it before rebuild and am still getting the same error.

**Comment by slrbl** [comment]
This could help you this https://github.com/docker/kitematic/issues/5029
Have a look and us know if it works

**Comment by nbogda** [comment]
Yes, that worked. I had to add the line
`discovery.type=single-node`
under the environment variables for elasticsearch to bypass the bootstrap error.

I was then getting an issue with not having enough memory for elasticsearch, so I had to increase the allowed memory resource in Docker. After fixing this, elasticsearch began working.

**Comment by slrbl** [comment]
Happy to hear it. I hope that you find Tornado useful. Don't hesitate start/share with your community!
