### ISSUE TITLE
 ActionView::Template::Error (File exists @ dir_s_mkdir - /myapp/tmp/cache/assets/sprockets/v3.0/2T):

### ISSUE THREAD

**Issue by nbogda** [slrbl/human-in-the-loop-machine-learning-tool-tornado#6]
Whenever I attempt to load 0.0.0.0:3000 I see this page.

![image](https://user-images.githubusercontent.com/21373166/79493876-163a0080-7ff0-11ea-8e27-00e26f6229db.png)

The error I am receiving from the terminal looks like this.

![image](https://user-images.githubusercontent.com/21373166/79493923-27830d00-7ff0-11ea-9ee7-d2f4f2bce0e8.png)

**Comment by slrbl** [comment]
Delete the content of ./tmp and restart

**Comment by nbogda** [comment]
I deleted the contents of tmp and restarted, but I was still getting the same error.

I fixed it by going into the subdirectory of v3.0 and manually deleting the files it was complaining about (2T and Qg) while the application was still running, and then refreshing the page. After doing this, I was able to login and upload a data set.

**Comment by slrbl** [comment]
Ok good
